# Shell variables
# Generated by 'wal'
wallpaper='/home/mark/Music/backupi3/wal/tetris_edit.png'

# Special
background='#181921'
foreground='#85c2e0'
cursor='#85c2e0'

# Colors
color0='#181921'
color1='#A2A83F'
color2='#DAE523'
color3='#E0ED21'
color4='#E4EC71'
color5='#29749C'
color6='#59F68D'
color7='#85c2e0'
color8='#5d879c'
color9='#A2A83F'
color10='#DAE523'
color11='#E0ED21'
color12='#E4EC71'
color13='#29749C'
color14='#59F68D'
color15='#85c2e0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
